//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::user::Entity as User;
pub use super::workspace::Entity as Workspace;
pub use super::workspace_invitation::Entity as WorkspaceInvitation;
pub use super::workspace_membership::Entity as WorkspaceMembership;
